services:

  db:
    image: postgis/postgis:15-3.4
    container_name: geo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo_admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump2.sql

  api:
    build: .
    container_name: geo_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/geo_admin

volumes:
  postgres_data: